trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: "Release"
  wwwrootDir: "Tailspin.SpaceGame.Web/wwwroot"
  dotnetSdkVersion: "6.x"

steps:
  - task: UseDotNet@2
    displayName: "Use .NET SDK $(dotnetSdkVersion)"
    inputs:
      version: "$(dotnetSdkVersion)"

  - task: Npm@1
    displayName: "Run npm install"
    inputs:
      verbose: false

  - script: dotnet restore --source "https://pkgs.dev.azure.com/MarcinGutmanski/PipelineTestProject/_packaging/MobileFabric/nuget/v3/index.json"
    displayName: "Add Packages in MobileFabric feed"

  - script: "./node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)"
    displayName: "Compile Sass assets"

  - task: gulp@1
    displayName: "Run gulp tasks"

  - script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
    displayName: "Write build info"
    workingDirectory: $(wwwrootDir)

  - task: DotNetCoreCLI@2
    displayName: "Restore project dependencies"
    inputs:
      command: "restore"
      projects: "**/*.csproj"

  - template: templates/build.yml
    parameters:
      buildConfiguration: "Debug"

  - template: templates/build.yml
    parameters:
      buildConfiguration: "Release"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Artifact: drop"
    condition: succeeded()
    
  - task: DownloadPackage@1
    inputs:
      packageType: 'nuget'
      feed: '/3468a477-489b-4e8e-831b-86886ea924e2'
      view: '42e16011-3912-4caf-bd22-653a5ce3fbb0'
      definition: 'a112bf70-7d7a-4d38-b172-934338893aa5'
      version: '*'
      downloadPath: '$(System.ArtifactsDirectory)'
